FROM maven AS builder

WORKDIR /app

COPY pom.xml .

COPY autoservice ./autoservice

WORKDIR /app/autoservice

RUN mvn clean package -Dcheckstyle.skip

FROM tomcat:10.0

WORKDIR /usr/local/tomcat/webapps/

RUN rm -rf /usr/local/tomcat/webapps/*

COPY --from=builder /app/autoservice/target/*.war ./ROOT.war

EXPOSE 8080