FROM maven:3.8-openjdk-17 AS builder

WORKDIR /app

COPY pom.xml .
COPY autoservice/pom.xml ./autoservice/
COPY autoservice/src ./autoservice/src/

RUN mvn clean package

FROM tomcat:10.0

RUN rm -rf /usr/local/tomcat/webapps/*

COPY --from=builder /app/autoservice/target/autoservice-1.0-SNAPSHOT.war /usr/local/tomcat/webapps/ROOT.war

EXPOSE 8080