#rules
rule.delete.order=true
rule.offset=true
rule.delete.place=true
rule.add.place=true

#data
standard.path.to.data=Autoservice/src/main/data/

#liquibase
db.driver=org.postgresql.Driver
db.url=jdbc:postgresql://carrepair:5432/carrepairdb
db.username=carrepair_admin
db.password=Admin
lb.changelog=classpath:liquibase/main.yml

#jwt
jwt.secret=lvfj123lwfkg5482iunxsak145dlhf23gbg6
jwt.lifetime=1800000
