#правила

rule.delete.order=true
rule.offset=true
rule.delete.place=true
rule.add.place=true

#наименование файлов .csv

standard.file.csv.garage=Garage.csv
standard.file.csv.orders=Order.csv
standard.file.csv.master=Master.csv
standard.file.csv.order_master=order_master.csv

#путь к data
standard.path.to.data=Autoservice/src/main/data/

#liquibase
db.driver=org.postgresql.Driver
db.url=jdbc:postgresql://localhost:5432/carrepairdb
db.username=carrepair_admin
db.password=Admin
lb.changelog=classpath:liquibase/changelog-v1.0.yml