lb.changelog=classpath:liquibase/changelog.yml
db.driver=org.postgresql.Driver
db.url=jdbc:postgresql://localhost:5432/bankdb
db.username=bank_admin
db.password=Admin
spring.kafka.bootstrap-servers=localhost:9092
management.tracing.enabled=false
management.observations.enable.spring.task.scheduling=false